heat_template_version: 2013-05-23

description: |
  This is a Heat template to deploy a single Cassandra node

parameters:

  image:
    description: Server Image used for all servers.
    type: string
    default: Ubuntu 12.04 LTS (Precise Pangolin)
    constraints:
    - allowed_values:
      - Ubuntu 12.04 LTS (Precise Pangolin)
      description: Must be a supported operating system.

  flavor:
    description: Web Cloud Server flavor
    type: string
    default: 2 GB Performance
    constraints:
    - allowed_values:
      - 2 GB Performance
      - 4 GB Performance
      - 8 GB Performance
      - 15 GB Performance
      - 30 GB Performance
      - 2GB Standard Instance
      - 4GB Standard Instance
      - 8GB Standard Instance
      - 15GB Standard Instance
      - 30GB Standard Instance
      description: |
        Must be a valid Rackspace Cloud Server flavor for the region you have
        selected to deploy into.

  # SSH Keypair
  ssh_keypair_name:
    description: "keypair name to register with Nova for the root SSH key"
    type: string

  ssh_public_key:
    type: string

  ssh_private_key:
    type: string

  seed:
    description: Seed node IP address
    type: string

  kitchen:
    label: Kitchen
    description: URL for the kitchen to use
    type: string
    default: https://github.com/rackspace-orchestration-templates/cassandra

  chef_version:
    label: Chef Version
    description: Version of chef client to use
    type: string
    default: 11.12.8

resources:

  node_server:
    type: "Rackspace::Cloud::Server"
    properties:
      name: cassandra-node%index%
      flavor: { get_param: flavor }
      image: { get_param: image }
      key_name: { get_param: ssh_keypair_name }

  node_setup:
    type: "OS::Heat::ChefSolo"
    depends_on: node_server
    properties:
      username: root
      private_key: { get_param: ssh_private_key }
      host: { get_attr: [node_server, accessIPv4] }
      kitchen: { get_param: kitchen }
      chef_version: { get_param: chef_version }
      node:
        cassandra:
          listen_address: { get_attr: [node_server, privateIPv4] }
          broadcast_address: { get_attr: [node_server, privateIPv4] }
          rpc_address: { get_attr: [node_server, privateIPv4] }
          seeds: [ { get_param: seed } ]
        java:
          jdk_version: 7
        rax:
          firewall:
            tcp: [7000]
          disk_config:
            mount_point: /var/lib/cassandra
        run_list: ["recipe[apt]",
                   "recipe[rax-disk-config]",
                   "recipe[cassandra::datastax]",
                   "recipe[rax-firewall]"]

outputs:
  public_ip:
    description: "Public IP of Cassandra node"
    value: { get_attr: [node_server, accessIPv4] }

  private_ip:
    description: "Private IP of Cassandra node"
    value: { get_attr: [node_server, privateIPv4] }
